runtime: python311
entrypoint: uvicorn app.main:app --host 0.0.0.0 --port $PORT

instance_class: F2

env_variables:
  QA_MODEL_TYPE: "extractive"
  QA_MODEL_NAME: "csarron/mobilebert-uncased-squad-v2"
  USE_FAISS: "false"

